trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_GOALS: 'clean test'
  ROOT_DIR: 'GAAM.Automation'  
  HTML_REPORT_PATH: 'reports/test-report.html'

steps:
- checkout: self
  fetchDepth: 0

- task: JavaToolInstaller@0
  displayName: 'Install JDK 20.0.2'
  inputs:
    versionSpec: '20.0.2'
    jdkArchitecture: 'x64'

- script: |
    java -version
    mvn -version
  displayName: 'Show java & maven versions'

- task: Maven@3
  displayName: 'Maven: clean and test'
  inputs:
    mavenPomFile: '$(ROOT_DIR)/pom.xml'
    goals: '$(MAVEN_GOALS)'
    options: '-B'             
    workingDirectory: '$(ROOT_DIR)'

- task: PublishTestResults@2
  displayName: 'Publish JUnit test results (if present)'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(ROOT_DIR)/target/surefire-reports/*.xml, $(ROOT_DIR)/target/failsafe-reports/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: false

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/reports
    if [ -f "$(ROOT_DIR)/$(HTML_REPORT_PATH)" ]; then
      cp "$(ROOT_DIR)/$(HTML_REPORT_PATH)" "$(Build.ArtifactStagingDirectory)/reports/test-report.html"
      echo "HTML report copied."
    else
      echo "WARNING: HTML report not found at $(ROOT_DIR)/$(HTML_REPORT_PATH)"
      # if you want to fail the pipeline when missing, replace the line above with: exit 1
    fi
  displayName: 'Collect HTML report'

- task: PublishPipelineArtifact@1
  displayName: 'Publish HTML report artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/reports'
    artifact: 'test-report'
    publishLocation: 'pipeline'
