trigger:
- main

pool:
  name: aws-agent-1

variables:
  pythonVersion: '3.9'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

- task: PowerShell@2
  displayName: Install Python dependencies
  inputs:
    targetType: inline
    errorActionPreference: stop
    script: |
      python -m venv .venv
      $py = Join-Path ".venv\Scripts" "python.exe"

      Write-Host "Upgrading pip"
      & $py -m pip install --upgrade pip

      $req = Join-Path "$(Build.SourcesDirectory)" "requirements.txt"
      if (Test-Path $req) {
        Write-Host "Installing from $req"
        & $py -m pip install -r $req
      } else {
        Write-Error "requirements.txt not found"
        exit 1
      }
    failOnStderr: false
