trigger:
  - main

pool:
  name: aws-agent-1   

variables:
  pythonVersion: '3.9' 

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

- powershell: |
    $src = Join-Path "$(Build.SourcesDirectory)" "src\main.py"
    Write-Host "Running file: $src"
    if (-not (Test-Path $src)) { Write-Error "File not found: $src"; exit 1 }
    python -m venv .venv
    .\.venv\Scripts\activate
    python -m pip install --upgrade pip
    if (Test-Path "$(Build.SourcesDirectory)\requirements.txt") { pip install -r "$(Build.SourcesDirectory)\requirements.txt" }
    python $src
  displayName: 'Create venv, install deps and run script'
  failOnStderr: true
