trigger:
- main

pool:
  name: aws-agent-1

variables:
  pythonVersion: '3.9'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

- task: PowerShell@2
  displayName: Install Python dependencies
  inputs:
    targetType: inline
    errorActionPreference: stop
    script: |
      $repo = "$(Build.SourcesDirectory)"
      Write-Host "Repo root: $repo"
      Write-Host "Top level files:"
      Get-ChildItem $repo

      python -m venv .venv
      $py = Join-Path ".venv\Scripts" "python.exe"
      & $py -m pip install --upgrade pip

      $req = Get-ChildItem -Path $repo -Filter requirements.txt -Recurse | Select-Object -First 1
      if (-not $req) {
        Write-Host "No requirements.txt found. Nothing to install."
        exit 0
      }

      Write-Host "Installing from $($req.FullName)"
      & $py -m pip install -r $req.FullName
    failOnStderr: false
